### PR TITLE
2017-04-28-daijiang-website: Fix a couple of urls

### PR DESCRIPTION
**Pull request by kbroman**
A couple of problem URLs:

- `/2017/04/25/yihui-website/` → `https://support.rbind.io/2017/04/25/yihui-website`
- `www.netlify.com` → `https://www.netlify.com`

### CODE REVIEW

**Comment by daijiang** [comment]
Hey @kbroman, it has been a while since talk with you! The first url (Yihui's introduction of his website) can actually be a relative one. Thanks for catching the second url.

**Comment by yihui** [comment]
@daijiang was correct about the first URL. The benefit of not using the full domain in the URL is that the link is relative, so that it works no matter what the domain is. For example, it works locally when you preview the site (requires a local server like **servr**), and we don't need to worry about such links if we decide to change the domain from support.rbind.io to other domains.

**Comment by kbroman** [comment]
Sorry to have made this so complicated!

**Comment by daijiang** [comment]
Not at all @kbroman !

**Pull request merged**
